server {
    listen 8080;
    listen [::]:8080;

    root /home/site/wwwroot;
    index index.php index.html index.htm;
    server_name fixpoint-be.azurewebsites.net;
    port_in_redirect off;

    # Default route
    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    # Playground route handler (rewrite to PHP script)
    location /playground {
        try_files $uri $uri/ /src/playground/index.php?$args;
    }

    # Show Laravel error pages or index.php debug output instead of generic NGINX 50x
    location = /50x.html {
        root /home/site/wwwroot;
    }

    # Block access to .git and other dotfiles
    location ~ /\.(?!well-known).* {
        deny all;
        access_log off;
        log_not_found off;
    }

    # PHP file handling
    location ~ [^/]\.php(/|$) {
        fastcgi_split_path_info ^(.+?\.php)(/.*)?$;
        fastcgi_pass 127.0.0.1:9000;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_param QUERY_STRING $query_string;
        fastcgi_param HTTP_PROXY "";
        fastcgi_intercept_errors on;

        # Performance tuning (can adjust based on load)
        fastcgi_connect_timeout         300;
        fastcgi_send_timeout           3600;
        fastcgi_read_timeout           3600;
        fastcgi_buffer_size 128k;
        fastcgi_buffers 4 256k;
        fastcgi_busy_buffers_size 256k;
        fastcgi_temp_file_write_size 256k;
    }
}
